// <auto-generated />
namespace EF_Code1st_Movie_Catalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleteDirectorAndYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteDirectorAndYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201908141934457_deleteDirectorAndYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
